name: stack-attack
services:
  backend:
    image: ghcr.io/kajvdv/stack-attack-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
      - LOBBIES_DIR=${LOBBIES_DIR}
      - GAME_SEED=${GAME_SEED}

  frontend:
    image: ghcr.io/kajvdv/stack-attack-frontend
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
