name: stack-attack
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
      - LOBBIES_DIR=${LOBBIES_DIR}
      - GAME_SEED=${GAME_SEED}

  frontend:
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
